on:
    pull_request:
        types: [opened, synchronize, reopened]
        paths: 
            - 'infra/azure/*'
    workflow_dispatch:

name: Azure IaC CI

permissions:
  id-token: write
  contents: read

jobs:
    build-environment-iac:
        name: Build Environment IaC
        uses: ./.github/workflows/shared.build-bicep.yml        
        with:
            BICEP_FILE: 'infra/azure/environment/main.bicep'
        secrets: 
            AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
            AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
            AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}