on:
    workflow_call:
      inputs:
        BICEP_FILE:
          required: true
          type: string
      secrets:
        AZURE_CLIENT_ID:
          required: true
        AZURE_TENANT_ID:
          required: true
        AZURE_SUBSCRIPTION_ID:
          required: true
  
permissions:
    id-token: write
    contents: read

jobs:
    build-bicep:
        name: Build Bicep
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Azure Login
              uses: azure/login@v2.1.1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}      
            - name: Bicep Lint
              shell: pwsh
              run: |
                az bicep build --file ${{ inputs.BICEP_FILE }}
